<template>
  <div>
    <canvas
    v-if="canvasId"
    class="ec-canvas"
    :canvasId="canvasId"
    @touchstart="touchStart"
    @touchmove="touchMove"
    @touchend="touchEnd"
    @error="error">
  </canvas>
  <canvas canvas-id="shareCanvas" class="shareCanvas" :style="{width:canvas.width+'px',height:canvas.height+'px'}"></canvas>
  </div>
</template>

<script>
import * as echarts from 'static/echarts'
import WxCanvas from './wx-canvas'

export default {
  props: {
    ec: {
      type: Object,
      default () {
        return {}
      }
    },
    canvasId: {
      type: String,
      default () {
        return 'ec-canvas'
      }
    },
    bookInfo: {
      type: Object
    },
    share: {
      type: Boolean
    }
  },
  data () {
    return {
      chart: null,
      img: '',
      canvas: {}
    }
  },
  watch: {
    share () {
      this.handleShare()
    }
  },
  onReady () {
    if (!this.ec) {
      console.warn('组件需绑定 ec 变量，例：<ec-canvas id="mychart-dom-bar" ' + 'canvas-id="mychart-bar" ec="{{ ec }}"></ec-canvas>')
      return
    }

    if (!this.ec.lazyLoad) {
      setTimeout(() => this.init(), 50)
    }
  },
  methods: {
    init () {
      const version = wx.version.version.split('.').map(n => parseInt(n, 10))
      const isValid = version[0] > 1 || (version[0] === 1 && version[1] > 9) || (version[0] === 1 && version[1] === 9 && version[2] >= 91)
      if (!isValid) {
        console.error('微信基础库版本过低，需大于等于 1.9.91。' + '参见： https://github.com/ecomfe/echarts-for-weixin' + '#%E5%BE%AE%E4%BF%A1%E7%89%88%E6%9C%AC%E8%A6%81%E6%B1%82')
        return
      }
      if (!this.ec.onInit) {
        console.warn('请传入 onInit 函数进行初始化')
        return
      }
      const { canvasId } = this
      const ctx = wx.createCanvasContext(canvasId)
      const canvas = new WxCanvas(ctx)
      echarts.setCanvasCreator(() => {
        return canvas
      })
      var query = wx.createSelectorQuery()
      query.select('.ec-canvas').boundingClientRect(res => {
        if (!res) {
          setTimeout(() => this.init(), 50)
          return
        }
        this.canvas.width = res.width
        this.canvas.height = Number(res.height) + 140
        console.log(this.ec.onInit(canvas, res.width, res.height, echarts))
      }).exec()
    },
    handleShare () {
      wx.showLoading({
        title: '正在生成图片'
      })
      let that = this
      wx.canvasToTempFilePath({
        canvasId: 'ec-canvas',
        fileType: 'jpg',
        success: function (radar) {
          let ctx = wx.createCanvasContext('shareCanvas')
          wx.downloadFile({
            url: 'https://wpimg.wallstcn.com/aca201c2-9c45-4e31-b625-b25a23b7e90f.jpg',
            success: function (qrcode) {
              let status = ''
              ctx.setFontSize(18)
              ctx.fillStyle = '#00A9BA'
              if (that.bookInfo) {
                if (that.bookInfo.status && that.bookInfo.status !== 0) {
                  that.bookInfo.status.sort(item => {
                    return item.timestamp - item.timestamp
                  })
                  switch (that.bookInfo.status[0].status) {
                    case 1:
                      status = '在读'
                      break
                    case 2:
                      status = '读过'
                      break
                    case 3:
                      status = '想读'
                  }
                  ctx.fillText(`我${status}这本书：`, 10, 22.5)
                }
                ctx.fillText(that.bookInfo.title, 20, that.canvas.height - 100)
                ctx.setFontSize(14)
                ctx.fillStyle = '#c0c0c0'
                ctx.fillText(that.bookInfo.author, 20, that.canvas.height - 80)
                ctx.fillText(that.bookInfo.publisher, 20, that.canvas.height - 60)
                ctx.fillText('豆瓣评分：' + that.bookInfo.rating.average, 20, that.canvas.height - 40)
              }
              ctx.setFontSize(12)
              ctx.fillText('Generated By 阅书录', 5, that.canvas.height - 5)
              ctx.drawImage(radar.tempFilePath, 0, 25, that.canvas.width, that.canvas.height - 145)
              ctx.drawImage(qrcode.tempFilePath, that.canvas.width - 75, that.canvas.height - 75, 75, 75)
              ctx.draw()
              setTimeout(() => {
                wx.canvasToTempFilePath({
                  canvasId: 'shareCanvas',
                  fileType: 'jpg',
                  success: function (allres) {
                    wx.hideLoading()
                    wx.saveImageToPhotosAlbum({
                      filePath: allres.tempFilePath,
                      success (success) {
                        wx.showToast({
                          title: '图片已保存',
                          icon: 'success'
                        })
                        console.log(success)
                      }
                    })
                  }
                })
              }, 500)
            }
          })
        }
      })
    },
    touchStart (e) {
      if (this.chart && e.touches.length > 0) {
        var touch = e.touches[0]
        this.chart._zr.handler.dispatch('mousedown', {
          zrX: touch.x,
          zrY: touch.y
        })
        this.chart._zr.handler.dispatch('mousemove', {
          zrX: touch.x,
          zrY: touch.y
        })
      }
    },
    touchMove (e) {
      if (this.chart && e.touches.length > 0) {
        var touch = e.touches[0]
        this.chart._zr.handler.dispatch('mousemove', {
          zrX: touch.x,
          zrY: touch.y
        })
      }
    },
    touchEnd (e) {
      if (this.chart) {
        const touch = e.changedTouches ? e.changedTouches[0] : {}
        this.chart._zr.handler.dispatch('mouseup', {
          zrX: touch.x,
          zrY: touch.y
        })
        this.chart._zr.handler.dispatch('click', {
          zrX: touch.x,
          zrY: touch.y
        })
      }
    }
  }
}
</script>

<style scoped >
.ec-canvas {
  width: 100%;
  height: 350px;
}
button {
  margin: 20px auto;
  font-size: 16px;
  line-height: 2;
  width: 50%;
}
.shareCanvas {
  position: absolute;
  top: -10000px;
}
</style>